# INICIALIZANDO UM NOVO REPOSITÓRIO
git init
# ADICIONA OS ARQUIVOS ATUAIS AO PRÓXIMO COMMIT
git add
# VERIFICAR O STATUS ATUAL DO REPOSITÓRIO GIT
git status
# CRIA UM NOVO COMMIT COM UMA MENSAGEM
git commit -m "mensagem"
# ENVIA AS ATUALIZAÇÕES PARA A NUVEM NA BRANCH ATUALMENTE ATIVA
git push
# PERMITE LISTAR E VER QUAL BRANCH ESTÁ ATIVA
git branch
# PERMITE MUDAR PARA UMA NOVA BRANCH
git checkout nome_da_branch
# PERMITE MUDAR E CRIAR UMA NOVA BRANCH COM BASE EM OUTRA
git checkout -b nome_da_branch_origem nome_nova_branch
# PERMITE FAZER O MERGE DA BRANCH ATIVA ATUALMENTE COM OUTRA BRANCH
git merge branch_a_receber_o_merge
# ATUALIZA A BRANCH ATUAL ATIVA
git pull
